shell zsh -lic 'command -v fastfetch >/dev/null 2>&1 && fastfetch; exec zsh -i'
adjust_line_height 115%
cursor_shape beam
cursor_trail 20
mouse_hide_wait 2.0
window_padding_width 5 10 5
window_margin_width 10 10 10
shell_integration enabled
enable_audio_bell no
font_size 11