adjust_line_height 115%
cursor_shape beam
cursor_trail 20
mouse_hide_wait 2.0
window_padding_width 3 8 5
window_margin_width 10 10 10
shell_integration enabled
enable_audio_bell no
font_size 11
include colors.conf