general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 150, 35
    position = 0, -100
    halign = center
    valign = center

    outline_thickness = 1
    rounding = 18

    outer_color = rgba(200,200,200,0.8)
    inner_color = rgba(0,0,0,0)
    font_color = rgba(255,255,255,0.8)

    check_color = rgba(112, 25, 37, 0.95)

    fail_color = rgba(200,200,200,0.8)
    fail_text =

    clear_on_fail = true
    placeholder_text =
    fade_on_empty = false

    dots_center = true
    dots_rounding = -1
    dots_size = 0.4
    dots_spacing = 0.25
}